### PR TITLE
Allow index name patterns in Privileges index fields

### PR DESCRIPTION
**Pull request by pquentin**
Motivated by [this YAML test](https://github.com/elastic/elasticsearch/blob/a04fd2668b82e0c4324b2cc8afe03eb9b0113ac2/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/roles/60_bulk_roles.yml#L39-L46) I realized that `index` in various privileges classes can always be an index pattern, ie. a string.

For references, here is how IndexName and Indices are defined:

```ts
export type IndexName = string
export type Indices = IndexName | IndexName[]
```

This fixes `security.bulk_put_role`, as can be tested with `make validate api=security.bulk_put_role branch=main`.

### CODE REVIEW

**Comment by flobernd** [comment]
That's unfortunate 😓 I recently changed these from `Indices` to `IndexName[]` without noticing it breaks validation..

Context:
https://github.com/elastic/elasticsearch-specification/pull/3016

**Review by l-trotta — APPROVED** [review]
LGTM! I think for most static clients this should change nothing since we already simplify this union as an array

**Comment by flobernd** [comment]
Could we please change this types to use `IndexName | IndexName[]` instead of the `Indices` alias for now and leave a comment that links to this issue?

That would give us some time to think about these special types that might carry specific semantics, without breaking the .NET client.

IMO we should model these differences in the Spec to some extend in order to allow generators to produce better code. In this particular case, `Indices` usually supports the `_all` string constant which is why the .NET client treats that in a special way. The security APIs however do not accept this constant. They require the usage of a proper pattern (`*`) instead.

We had similar candidates in the past where the typing is the same, but the semantics are different. I remember e.g. `StoredFields` (#2415). Here we used the same workaround, keeping the special `StoredFields` properties as `Field | Field[]` while using `Fields` for everything else.

**Comment by pquentin** [comment]
Thanks Florian, please take another look.

**Review by flobernd — APPROVED** [review]
Thank you! This looks good now 🙂

**Pull request merged**
