### PR TITLE
Add ml.update_trained_model_deployment API

### PR DESCRIPTION
**Pull request by pquentin**
I'm not sure if it should be added or not, as this API is currently in beta.

### CODE REVIEW

**Comment by davidkyle** [comment]
Elasticsearch is updated to make this API GA in https://github.com/elastic/elasticsearch/pull/108868

The same PR also adds `number_of_allocations` as a query param

**Comment by pquentin** [comment]
@davidkyle What are your thoughts on merging this now, and then updating when the query parameters are available? For clients this makes no difference, the usage is the same.

**Comment by davidkyle** [comment]
The PR that adds the query param (https://github.com/elastic/elasticsearch/pull/108868) is now merged, can the query param be added now?

**Comment by davidkyle** [comment]
The API spec still says `beta` and needs updating from the ES repo. 

https://github.com/elastic/elasticsearch-specification/blob/e54499c8be3645d78f18c0692da4759ed2cd2984/specification/_json_spec/ml.update_trained_model_deployment.json#L7

**Comment by pquentin** [comment]
I was thinking we could reflect the current reality in order to ship that today in 8.13, and then when 8.14.1 goes out we can update with the beta label and query parameters.

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
> I was thinking we could reflect the current reality in order to ship that today in 8.13, 

👍 I added the backport 8.13 label

**Pull request merged**
