### PR TITLE
[Connector API] Add missing 8.14 changes

### PR DESCRIPTION
**Pull request by jedrazb**
### Changes

Adding missing Connector API features that were shipped in 8.14 after #2367 was merged. 

2 new endpoints:
- validate draft filtering
- activate draft filtering

2 endpoint changes
- update filtering endpoint takes now `rules` and `advanced_snippet` as optional params, `filtering` is now optional (still present for backward compatibility)
- delete connector endpoint accepts `delete_sync_jobs` url param

filtering-related timestamps (rules and advanced_snippet) were made optional in ES backend in `8.14`

### CODE REVIEW

**Comment by l-trotta** [comment]
From the other PR: [FilteringConfig](https://github.com/elastic/elasticsearch-specification/blob/4718254e0ea2bab696610ef8e141c140d116fa6e/specification/connector/_types/Connector.ts#L208) -> `active` and `draft` should be optional, `domain` should be removed, it seems like an [internal parameter](https://github.com/elastic/elasticsearch/blob/119f81f04305b91b9bfe9866525888ef17d35423/x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/ConnectorFiltering.java#L47)

**Comment by jedrazb** [comment]
> From the other PR: [FilteringConfig](https://github.com/elastic/elasticsearch-specification/blob/4718254e0ea2bab696610ef8e141c140d116fa6e/specification/connector/_types/Connector.ts#L208) -> `active` and `draft` should be optional

@l-trotta  I'm not sure if they should become optional, they are always [required](https://github.com/elastic/elasticsearch/blob/119f81f04305b91b9bfe9866525888ef17d35423/x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/ConnectorFiltering.java#L99) in the Filtering config representation in the server implementation

> domain should be removed, it seems like an [internal parameter](https://github.com/elastic/elasticsearch/blob/119f81f04305b91b9bfe9866525888ef17d35423/x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/ConnectorFiltering.java#L47)

Yes, `domain` is not part of the request payload for any endpoint, but we do [populate](https://github.com/elastic/elasticsearch/blob/119f81f04305b91b9bfe9866525888ef17d35423/x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/ConnectorFiltering.java#L107) it in the index and return in the response when getting/listing connectors (the response is `Connector` or `Connectors[]`). We still need to populate it (even with the default value) as this is required by the Connector Protocol. 

If I remove this from the [FilteringConfig](https://github.com/elastic/elasticsearch-specification/blob/4718254e0ea2bab696610ef8e141c140d116fa6e/specification/connector/_types/Connector.ts#L208) could it impact e.g. the get connector response from clients? (as `Connector` type references `filtering: FilteringConfig[]`)

I'm unsure how to handle that case correctly in clients

**Comment by l-trotta** [comment]
Sorry for the confusion, I didn't understand how the `filtering` field was outputted differently if used in the context of SyncJobs. The correct fix is to replace `FilteringConfig` with `FilteringRules` in `SyncJobConnectorReference`. [Server code](https://github.com/elastic/elasticsearch/blob/3e0568a102de0d95f60402164195159803e2a6f6/x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/Connector.java#L87)

**Comment by l-trotta** [comment]
`features' in [Connector](https://github.com/elastic/elasticsearch-specification/blob/1e21ace2facb4fc95701bcffc92905ef8aa8d6ae/specification/connector/_types/Connector.ts#L244) should be [nullable](https://github.com/elastic/elasticsearch/blob/3e0568a102de0d95f60402164195159803e2a6f6/x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/Connector.java#L84)

**Comment by jedrazb** [comment]
> The correct fix is to replace FilteringConfig with FilteringRules in SyncJobConnectorReference

Thank you for catching this! 👍

**Review by l-trotta — APPROVED** [review]
LGTM!

**Comment by jedrazb** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.14|[](https://github.com/elastic/elasticsearch-specification/pull/2540)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
