### PR TITLE
Fix update_by_query request

### PR DESCRIPTION
**Pull request by philkra**
as titled.

### CODE REVIEW

**Review by delvedor — COMMENTED** [review]
According to the [doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/query-dsl-range-query.html), the range query should be an object and not an array.
@swallez can you double check the ES source code to understand what's going on here?

**Comment by swallez** [comment]
Confirmed after looking at the ES code: there's no support for arrays there.

**Comment by philkra** [comment]
Ack, I'll dig how to resolve this.

**Comment by philkra** [comment]
Opened https://github.com/elastic/elasticsearch/pull/77700 to fix the test upstream.

**Pull request closed without merging**
