### PR TITLE
Break function_score out into single- and multi-function types

### PR DESCRIPTION
**Pull request by JoshMock**
Fixes https://github.com/elastic/elasticsearch-specification/issues/2109.

### CODE REVIEW

**Comment by l-trotta** [comment]
`FunctionScoreQuery` was recently updated with the `@shortcut` property which allowed us to accept every variant of the query, are we sure we need this?

**Comment by JoshMock** [comment]
I'm not entirely sure `@shortcut_property` covers all of this. As @swallez [noted here](https://github.com/elastic/elasticsearch-specification/issues/2109#issuecomment-1569808519), the issue is that all the properties of `FunctionScoreContainer` can be used on the same level as `boost_mode`, `max_boost`, etc. OR a `functions` property can be provided that includes one function object or an array of function objects.

**Review by pquentin — APPROVED** [review]
Thanks! LGTM.

**Comment by l-trotta** [comment]
we need to rename FunctionScoreContainer, the java generator (and maybe others?) removes the "Container" part of the name, and since FunctionScore already exists there's a duplicate error. Does FunctionScoreCommonContainer sounds okay?

**Comment by l-trotta** [comment]
After discussing it with the other static clients maintainer we have decided that supporting this would require too much effort compared to the benefits (since it's not a unique feature, but just an alternative syntax). If we were to discover a case where this is absolutely necessary to implement in the dynamic clients then we can review this solution again as a starting point and the static client can ignore it from the generator.

**Comment by JoshMock** [comment]
Thanks @l-trotta!

**Pull request closed without merging**
