### PR TITLE
[Backport 8.x][OpenAPI] Remove self-referential externalDocs (#2925)

### PR DESCRIPTION
**Pull request by lcawl**
Backports https://github.com/elastic/elasticsearch-specification/pull/2925

### CODE REVIEW

**Comment by pquentin** [comment]
@lcawl We don't usually request review for backports, was there anything especially trick here?

**Review by l-trotta — APPROVED** [review]
(had to rebase it to merge it) LGTM!

**Comment by lcawl** [comment]
> @lcawl We don't usually request review for backports, was there anything especially tricky here?

Ah, all the other repos I have to get approval, so if that isn't the case here I must have missed it. Thanks for the clarification!

**Comment by pquentin** [comment]
Kibana and Elasticsearch have backporting automation that doesn't require reviews, but indeed for manual backports the rule is specific to this repo!

**Pull request merged**
