### PR TITLE
Add task to clean npm dependencies

### PR DESCRIPTION
**Pull request by philkra**
make task for https://github.com/elastic/elasticsearch-specification/pull/990

### CODE REVIEW

**Comment by sethmlarson** [comment]
Alternate suggestion: should setup-env automatically do this since they're no-ops on the initial setup?

**Review by delvedor — CHANGES_REQUESTED** [review]
There is no need to clean the lockfile now, it's committed to the repo so we'll always have the same dependencies installed :)

**Comment by philkra** [comment]
@sethmlarson good call, I added the task to `setup-env`.

@delvedor , removed the deletion of lockfiles

**Review by delvedor — APPROVED** [review]
LGTM

**Pull request merged**
