### PR TITLE
Change required_native_memory_bytes type to ByteSize

### LINKED ISSUE #2739: Wrong type for required_native_memory_bytes (TrainedModelSizeStats  class)
## 🐛 Wrong type
The [TrainedModelSizeStats class](https://github.com/elastic/elasticsearch-specification/blob/8711e52d563766c06424b69b01e60f25a140ce13/specification/ml/_types/TrainedModel.ts#L130) has the wrong type for `required_native_memory_bytes`, it is marked as `integer` but should be `ByteSize`. This is causing the spec to have the wrong type, and the auto-generated clients like the .NET one to [always fail](https://github.com/elastic/elasticsearch-net/issues/8271) when deserializing the response.

## Definition
```diff
export class TrainedModelSizeStats {
  /** The size of the model in bytes. */
  model_size_bytes: ByteSize
  /** The amount of memory required to load the model in bytes. */
- required_native_memory_bytes: integer
+ required_native_memory_bytes: ByteSize
}
```

### PR DESCRIPTION
**Pull request by svalbuena**
Fixes #2739. The required_native_memory_bytes represents a value in bytes, an integer is too small to fit the range, and other bytes parameters in the spec are already using the ByteSyze type.

### CODE REVIEW

**Comment by maxhniebergall** [comment]
Hi @svalbuena, thanks for reporting and fixing this issue! Due to an issue with our CI, we need to have a PR from a branch in this repo to main. I've merged your PR into a local branch, and I will open a new PR to merge this new branch into main. Another PR has also been opened to backport this bugfix to the latest release.

**Comment by maxhniebergall** [comment]
https://github.com/elastic/elasticsearch-specification/pull/2743
https://github.com/elastic/elasticsearch-specification/pull/2742

**Comment by maxhniebergall** [comment]
Your changes have been merged. Thanks for this contribution, and congrats on merging your first elastic PR!

**Comment by svalbuena** [comment]
Thank you! Whats the process of updating the .net client repo with the new autogenerated code? @maxhniebergall

**Comment by maxhniebergall** [comment]
@svalbuena, because we backported the code to v8.15.0, the new generated client code will be available with the v8.15.0 release which is happening very soon.

**Pull request merged**
