### PR TITLE
[DOCS] Add ApplicationPrivileges param descs

### PR DESCRIPTION
**Pull request by lockewritesdocs**
Adds missing parameter descriptions for the `ApplicationPrivileges` type.

### CODE REVIEW

**Review by delvedor — CHANGES_REQUESTED** [review]
Thanks! Can you run `make contrib` and push the changes? :)

**Comment by lockewritesdocs** [comment]
> Thanks! Can you run `make contrib` and push the changes? :)

I knew that I was missing a step but didn't know what it was 😆 Thanks for the tip @delvedor. I just pushed the most recent changes.

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by delvedor** [comment]
I did the backport myself.
It should be automated, but it seems the GitHub action is not working at the moment.

**Pull request merged**
