### PR TITLE
Add support for new timezone field in watch schedules

### PR DESCRIPTION
**Pull request by lukewhiting**
This change adds timezone support to Watcher schedules added in https://github.com/elastic/elasticsearch/pull/117033

### CODE REVIEW

**Comment by lukewhiting** [comment]
I'm trying to run the validation locally (Ubuntu 24.04) to get more info about the fails on the `watcher.put_watch` endpoint however I get this when running `make validate api=watcher.put_watch type=request branch=main`:

```text
✖ 
    at run (/home/lukewhiting/code/elasticsearch-specification/compiler/run-validations.js:114:12)
    exit code: 1
make: *** [Makefile:4: validate] Error 1

```

**Review by pquentin — APPROVED** [review]
Thank you! The failures are unrelated (https://github.com/elastic/elasticsearch-specification/pull/3188 fixes most of them), and I'll reach out to you offline to fix `make validate`. 

This change isn't tested because we don't currently use the watcher plugin from the Elasticsearch YAML tests, but I'd love to do it at some point.

**Comment by pquentin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch-specification/pull/3189)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by pquentin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch-specification/pull/3190)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
