### PR TITLE
Mark Synonyms API as stable

### PR DESCRIPTION
**Pull request by kderusso**

### CODE REVIEW

**Review by carlosdelest — APPROVED** [review]

**Review by Mikep86 — APPROVED** [review]
LGTM

**Review by pquentin — APPROVED** [review]
Thanks! In what version do they become stable? (Wondering if this should be backported to the 8.12 branch.)

**Comment by kderusso** [comment]
> Thanks! In what version do they become stable? (Wondering if this should be backported to the 8.12 branch.)
@pquentin  This is planned for 8.13! Thanks for asking!

**Comment by codebrain** [comment]
> Thanks! In what version do they become stable? (Wondering if this should be backported to the 8.12 branch.)

Marked as Stable in 8.10:
https://github.com/elastic/elasticsearch/pull/97962/files

Please ensure online docs are updated too as they are showing the API is in beta (which is incorrect):
image

**Comment by pquentin** [comment]
The docs built from the main branch (that will become 8.13) are already correct: https://www.elastic.co/guide/en/elasticsearch/reference/master/synonyms-apis.html

**Pull request merged**
