### PR TITLE
Add spec for bulk put roles

### PR DESCRIPTION
**Pull request by jfreden**
This adds a new spec for the bulk put roles API added in 8.15 in https://github.com/elastic/elasticsearch/pull/109339.

### CODE REVIEW

**Comment by jfreden** [comment]
Hey @pquentin ! I've created a new PR here and can't run the failing validation locally because I don't have the needed vault permissions. Thanks!

**Comment by pquentin** [comment]
Hey @jfreden, I'll reach to you privately about this. In the meantime, I can tell you that the error is that Elasticsearch YAML tests [call the bulk put role API with a description](https://github.com/elastic/elasticsearch/blob/3802d84429f14d1cae5a39fc24449f9d8ecd0ea5/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/roles/60_bulk_roles.yml#L49) but that field is missing from [Role Descriptor](https://github.com/elastic/elasticsearch-specification/blob/25975f4de56ce3bedc03cd9d56c113c915191dc5/specification/security/_types/RoleDescriptor.ts#L28-L56).

**Comment by jfreden** [comment]
Great success! Thanks @pquentin ! I was able to run this locally too. 👍

**Comment by pquentin** [comment]
(Sorry for the noise, I've been testing credential changes with this pull request.)

**Comment by l-trotta** [comment]
sorry I know this is again something not strictly related to the PR, but since the `cluster` field only accepts cluster privilege values, should we change it from string[] to `ClusterPrivilege[]`?

**Comment by l-trotta** [comment]
other than that, LGTM!

**Comment by jfreden** [comment]
Thanks for the review @l-trotta ! I've updated the `RoleDescriptor` to use the enum for `ClusterPrivilege`.

**Review by l-trotta — APPROVED** [review]

**Pull request merged**
