### PR TITLE
Add specification for new sparse vector query; deprecate specification for text_expansion and weighted_tokens queries

### PR DESCRIPTION
**Pull request by kderusso**
Adds specification for the new `sparse_vector` query and deprecates the specifications for `text_expansion` and `weighted_tokens` queries.

### CODE REVIEW

**Comment by l-trotta** [comment]
if I got this right every sparse query should have either `query_vector` or `inference_id`, the way we model this to have it checked client side is to add `/** @variants container */` on top of the class and mark all properties that can always be added with `@variant container_property`, an example of this is [PinnedQuery](https://github.com/elastic/elasticsearch-specification/blob/4a3a7aee6783a8fe9e6e2cb1dc07da4aeb6773ea/specification/_types/query_dsl/specialized.ts#L235) where you must set either `ids` or `docs`

**Comment by kderusso** [comment]
> if I got this right every sparse query should have either query_vector or inference_id, the way we model this to have it checked client side is to add /** @variants container */ on top of the class and mark all properties that can always be added with @variant container_property, an example of this is [PinnedQuery](https://github.com/elastic/elasticsearch-specification/blob/4a3a7aee6783a8fe9e6e2cb1dc07da4aeb6773ea/specification/_types/query_dsl/specialized.ts#L235) where you must set either ids or docs

Thanks @l-trotta! I think I got this right?

**Comment by l-trotta** [comment]
almost! all properties that aren't `query_vector` or `inference_id` should be `@variant container_property`, so not just `field`. basically this is to assure that either `query_vector` or `inference_id` are set, but not both of them, while all the other properties are unaffected by this check.

**Review by l-trotta — APPROVED** [review]
LGTM!

**Pull request merged**
