### PR TITLE
Add variants to analysis classes, Add IndexState.data_stream

### PR DESCRIPTION
**Pull request by sethmlarson**
Most of this is adding `@variant` to analyzers, tokenizers, token filters and char filters.

Added `IndexState.data_stream?` to close https://github.com/elastic/elasticsearch-specification/issues/532

### CODE REVIEW

**Review by delvedor — APPROVED** [review]
Great work! ❤️

**Comment by sebelga** [comment]
@sethmlarson You closed #532 for the `IndexState.data_stream` but I am not seeing the missing `settings.index.hidden` as part of this PR. Is this correct?

**Comment by sethmlarson** [comment]
@sebelga Hmm, I saw [`@aliases index.hidden` on the `hidden` property](https://github.com/elastic/elasticsearch-specification/blob/main/specification/indices/_types/IndexSettings.ts#L77) and figured that solved the issue. @delvedor is that sufficient for this case or does more need to be done to make this value accessible?

**Comment by sebelga** [comment]
Oh I see it got added in a previous PR. Thanks @delvedor

**Pull request merged**
