### PR TITLE
[Proposal] Transform script into a container

### PR DESCRIPTION
**Pull request by Anaethelion**
`@shortcut_property` on `InlineScript` is unreachable from the union.
From the server code, `Script` could benefit from being a container instead.

### CODE REVIEW

**Review by swallez — COMMENTED** [review]
If we're going that route, I would go as far as not making it a container: `lang` and `options` only apply to inline script, so it's weird to allow `id` _xor_ `source` while having these container properties that will cause a server-side failure if set for the wrong variant.

**Comment by Anaethelion** [comment]
I'm OK with merging everything in the same interface.
pinging @l-trotta @flobernd for visibility!

**Comment by flobernd** [comment]
I like the container solution a little bit better over the single interface, but no strong preference here. Fine with a single interface as well. This is definitely better than what we currently have.

**Comment by l-trotta** [comment]
RoleTemplateInlineScript has duplicate fields from ScriptBase, we should remove lang and options

**Comment by l-trotta** [comment]
LGTM but it breaks deserialization for RoleTemplateScript the java client, if we could wait until I fix it before merging this

**Review by swallez — APPROVED** [review]
LGTM.

**Review by flobernd — APPROVED** [review]

**Review by l-trotta — APPROVED** [review]

**Pull request merged**
